config:
  line-length:
    line_length: 120

ignores:
  - "CHANGELOG.md"

overrides:
  - filter:
      - "docs/**/*.md"
    combine: merge
    config:
      first-line-h1: false

noBanner: true
noProgress: true
