try:
    # _version.py file is auto-generated by setuptools_scm during the build process
    from ._version import __version__
except ImportError:
    __version__ = "unknown"

__all__ = ["__version__"]
